pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh 'echo Should some java code here but it has an access error which I couldn't resolve'
            }
        }
        stage('Complete') {
            steps {
                sh 'echo Job completed'
            }
        }
    }
}
